name: sprintf
version: 1.0.3
author: Richard Eames <dartsprintf@naddiseo.ca>
description: Dart implementation of sprintf
homepage: https://github.com/Naddiseo/dart-sprintf
dependencies:
  unittest: any
