name: sprintf
version: 1.0.1-alpha1
description:  >
  Dart implementation of sprintf
author: Richard Eames <dartsprintf@naddiseo.ca>
homepage: https://github.com/Naddiseo/dart-sprintf
dependencies:
  unittest:
    sdk: unittest
